---
- hosts: tag_Name_MediaWiki_Blue
  user: ec2-user
  gather_facts: false
  vars:
    mediawiki_url: "https://releases.wikimedia.org/mediawiki/1.34/mediawiki-core-1.34.2.tar.gz"


  tasks:
  - name: Current user
    shell: whoami
    register: result

  - name: Print user name 
    debug:
      var: result.stdout

  - name: Copy shell script to remote machine
    copy:
      src: ./mediawiki_apache_config.sh
      dest: /home/ec2-user/mediawiki_apache_config.sh
      owner: ec2-user
      group: ec2-user
      mode: '0755'    
      force: yes

  - name: Run shell script on remote machine
    become: yes
    shell: /home/ec2-user/mediawiki_apache_config.sh {{ mediawiki_url|quote }}
    args:
      chdir: /home/ec2-user
    register: result

  - name: Print output of shell script
    debug:
      var: result.stdout     

